name: benchmark

dependencies:
  - python==3.9
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python
    - lxml
    - tqdm
    - tensorflow
    - seaborn
    - absl-py
    - easydict
    - pillow
    - nest_asyncio
    - pyshark
    - ntplib
    - psutil
    - scipy
    - speedtest-cli
    - pocketsphinx
    - SpeechRecognition
    - numpy
    - pydub
    - aeneas