name: tracking-yolov4-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - tensorflow==2.3.0
    - seaborn
    - absl-py
    - easydict
    - flask
    - flask-mqtt
    - pillow
    - requests
    - requests-toolbelt
    - pika
    - slixmpp
    - websockets
    - aiocoap
    - rticonnextdds_connector
    - paho-mqtt
    - nest_asyncio
    - pyshark
    - ntplib
    - aioquic
    - psutil